//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fond
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фонды_отчёты
    {
        public int ID_отчёта { get; set; }
        public Nullable<int> Год_договора { get; set; }
        public string Номер_договора { get; set; }
        public string Название { get; set; }
        public string Организации { get; set; }
        public string Ответственный_исполнитель { get; set; }
        public string Примечание { get; set; }
        public string Ссылка_корневая { get; set; }
        public string Ссылка_текст_отчета { get; set; }
        public string Ссылка_таблицы { get; set; }
        public string Ссылка_графические { get; set; }
        public string Ключевые_слова { get; set; }
        public string Аннотация { get; set; }
        public string Пользователь { get; set; }
        public Nullable<System.DateTime> Дата_заполнения { get; set; }
    }
}
